#!/bin/sh

# Find the custom config file in either './config' or './scripts';
CFG="$(find . -name "*_phpcs.xml" | egrep '^./(config|scripts)')"
PHPCS_PARAMS="--warning-severity=0"
if [ "$1" = "--drupalpractice" ] || [ "$2" = "--drupalpractice" ]; then
  # Use the coding standard 'DrupalPractice'
  CFG="./vendor/drupal/coder/coder_sniffer/DrupalPractice/ruleset.xml"
  PHPCS_PARAMS=""
elif [ "$CFG" = "" ]; then
  CFG="./vendor/remko79/coding-standards/drupal_cs.xml"
fi
echo "Using configuration file: ${CFG}"

PHPCS="./vendor/bin/phpcs --standard=${CFG} -p --report=full ${PHPCS_PARAMS}"
echo ${PHPCS}
if [ "$1" = "diff" ]
then
    # This allows the user to run phpcs on all the staged and unstaged files.
    CHANGED_FILES=$(git status --porcelain | grep "^??\|^\ M" | cut -c 4-)
elif [ "$1" = "staged" ]
then
    # All git staged files
    CHANGED_FILES=$(git diff --cached --name-status | egrep "^(M|A)" | cut -c 3-)
else
    # All files
    CHANGED_FILES="ALL FILES"
fi

if [ -d "./web/modules/custom" ]; then
    # Drupal 8
    DIRS="./web/modules/custom ./web/themes"
    if [ -d "./behat" ]; then
        DIRS="${DIRS} ./behat"
    fi
elif [ -d "./sites/all/modules/custom" ]; then
    # Drupal 7
    DIRS="./sites/all/modules/custom ./sites/all/themes"
else
    # Everything
    DIRS="."
fi

if [ "$CHANGED_FILES" = "ALL FILES" ]; then
    echo "Running Code Sniffer on: ${DIRS}"
    ${PHPCS} ${DIRS}

    if [ $? != 0 ]
    then
        echo "PHP Code Style errors found."
        exit 1
    fi
elif [ "$CHANGED_FILES" != "" ]; then
    echo "Running Code Sniffer on:"
    echo "$CHANGED_FILES"
    ${PHPCS} ${CHANGED_FILES}

    if [ $? != 0 ]
    then
        echo "PHP Code Style errors found."
        exit 1
    fi
fi

exit 0;
